<a href="https://colab.research.google.com/github/aashutoshkumarbhardwaj/today1/blob/master/day34.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#handeling date and time variable -python
import numpy as np
import pandas as pd

In [2]:
date= pd.read_csv('/content/sample_data/orders.csv')
time=pd.read_csv('/content/sample_data/messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [9]:
#coverting to date andf time datatype
date['date']=pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [10]:
#extract year
date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
204 2018-10-07         820       30       2       2018
496 2019-03-16        3562       23       1       2019
154 2018-10-10         803       23       2       2018
591 2019-10-15        5386       25       2       2019
930 2018-09-06        6716       16       4       2018

In [11]:
#extract month
date['date_month']=date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
916 2019-07-13        2457        3      25       2019           7
203 2019-12-16        4033        4       1       2019          12
448 2018-12-07        1933       21      17       2018          12
209 2018-11-06        3234       25       1       2018          11
772 2018-11-05        6845       13       3       2018          11

In [12]:
date['date_month_name']=date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name
252,2019-01-25,792,25,1,2019,1,January
330,2019-03-02,2432,22,3,2019,3,March
112,2019-03-21,5787,13,134,2019,3,March
463,2018-11-21,1945,9,3,2018,11,November
960,2018-09-30,954,2,1,2018,9,September

In [13]:
#extract days

date['date_day']=date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
233,2019-08-17,2411,23,6,2019,8,August,17
930,2018-09-06,6716,16,4,2018,9,September,6
293,2018-09-12,3151,26,1,2018,9,September,12
16,2019-04-10,977,22,1,2019,4,April,10
124,2018-11-22,1440,16,23,2018,11,November,22

In [14]:
#days of week

date['date_dow']=date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
783,2019-08-11,582,26,3,2019,8,August,11,6
204,2018-10-07,820,30,2,2018,10,October,7,6
160,2019-11-28,2627,16,1,2019,11,November,28,3
73,2019-07-28,3913,13,19,2019,7,July,28,6
904,2019-06-17,1828,0,1,2019,6,June,17,0

In [15]:
#days of weeek name
date['date_dow_name']=date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [16]:
#is weekends?
date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
408,2019-05-31,1341,13,8,2019,5,May,31,4,Friday,0
178,2019-04-30,4776,16,100,2019,4,April,30,1,Tuesday,0
113,2018-12-15,6288,2,2,2018,12,December,15,5,Saturday,1
894,2019-07-10,1533,18,82,2019,7,July,10,2,Wednesday,0
591,2019-10-15,5386,25,2,2019,10,October,15,1,Tuesday,0

In [18]:
#extrat weeks of year
#extrat weeks of year
date['date_week']=date['date'].dt.isocalendar().week
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
896,2019-05-29,4586,22,2,2019,5,May,29,2,Wednesday,0,22
188,2019-06-25,1123,25,1,2019,6,June,25,1,Tuesday,0,26
444,2019-07-24,6115,22,29,2019,7,July,24,2,Wednesday,0,30
280,2018-08-18,6716,16,2,2018,8,August,18,5,Saturday,1,33
746,2019-02-01,6632,22,5,2019,2,February,1,4,Friday,0,5

In [19]:
#extract quator
date['quarter']=date['date'].dt.quarter
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
64,2019-06-01,3541,2,5,2019,6,June,1,5,Saturday,1,22,2
792,2019-03-31,5843,9,1,2019,3,March,31,6,Sunday,1,13,1
536,2019-04-24,1140,26,2,2019,4,April,24,2,Wednesday,0,17,2
587,2019-10-30,6153,22,6,2019,10,October,30,2,Wednesday,0,44,4
124,2018-11-22,1440,16,23,2018,11,November,22,3,Thursday,0,47,4

In [20]:
#extract semester
date['semester']=np.where(date['quarter'].isin([1,2]),1,2)
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
112,2019-03-21,5787,13,134,2019,3,March,21,3,Thursday,0,12,1,1
203,2019-12-16,4033,4,1,2019,12,December,16,0,Monday,0,51,4,2
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
515,2019-06-22,4611,26,8,2019,6,June,22,5,Saturday,1,25,2,1
151,2019-10-15,5066,18,14,2019,10,October,15,1,Tuesday,0,42,4,2

In [21]:
#extract time elapsed btw dates

import datetime
today=datetime.datetime.today()
today

datetime.datetime(2025, 4, 27, 23, 49, 34, 361273)

In [24]:
today - date['date']

0     0 days
1     0 days
2     0 days
3     0 days
4     0 days
       ...
995   0 days
996   0 days
997   0 days
998   0 days
999   0 days
Name: date, Length: 1000, dtype: timedelta64[ns]

In [25]:
(today - date['date']).dt.days

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: date, Length: 1000, dtype: int64

In [27]:
#month passed
np.round((today- date['date'])/np.timedelta64(1,'m'),0)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: date, Length: 1000, dtype: float64

In [28]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [29]:
#converting to datetime datatype
time['date']=pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [30]:
time['hours']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second
time.head()

,date,msg,hours,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [31]:
#extract time part
time['time']=time['date'].dt.time
time.head()

,date,msg,hours,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [32]:
#time difference
today-time['date']

0     2185 days 23:10:00
1     1568 days 00:20:00
2     2122 days 23:39:00
3     1722 days 23:29:00
4     1897 days 00:49:00
             ...
995   2396 days 23:10:00
996   1777 days 00:46:00
997   2394 days 00:23:00
998   2445 days 00:26:00
999   1943 days 00:35:00
Name: date, Length: 1000, dtype: timedelta64[ns]

In [33]:
# in secnds
(today-time['date'])/np.timedelta64(1,'s')

0      188867400.0
1      135476400.0
2      183425940.0
3      148865340.0
4      163903740.0
          ...
995    207097800.0
996    153535560.0
997    206842980.0
998    211249560.0
999    167877300.0
Name: date, Length: 1000, dtype: float64

In [34]:
#in minutes
(today-time['date'])/np.timedelta64(1,'m')

0      3147790.0
1      2257940.0
2      3057099.0
3      2481089.0
4      2731729.0
         ...
995    3451630.0
996    2558926.0
997    3447383.0
998    3520826.0
999    2797955.0
Name: date, Length: 1000, dtype: float64

In [35]:
# in hours
(today-time['date'])/np.timedelta64(1,'h')

0      52463.166667
1      37632.333333
2      50951.650000
3      41351.483333
4      45528.816667
           ...
995    57527.166667
996    42648.766667
997    57456.383333
998    58680.433333
999    46632.583333
Name: date, Length: 1000, dtype: float64